version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "postgres"]
      interval: 5s
      timeout: 1s
      retries: 2